version: '3'
services:

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - 27037:27017

  etl:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb

  postgresdb:
    image: postgres
    ports:
    - "5556:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=tweeter

  slackbot:
    build: slackbot/
    volumes:
    - ./slackbot/:/app
    depends_on:
    - postgresdb   
  
    